### PR TITLE
Handle http errors

### PR DESCRIPTION
**Pull request by Toniob**
I had issues with some albums where a track lyrics cannot be found. Picard stayed in a loading informations state, with an impossible to load error after some time.

### CODE REVIEW

**Comment by protodeniz** [comment]
Looks quite nice. Thanks. The thing is, it would be nice if you could keep the indentation as is. Then I will merge it!

**Comment by Toniob** [comment]
I’ve changed it because it is the recommended way : https://peps.python.org/pep-0008/#indentation . If you want tabs back, i’ll do it, but I think it’s better if we do it the python way.

**Comment by protodeniz** [comment]
> I’ve changed it because it is the recommended way : https://peps.python.org/pep-0008/#indentation . If you want tabs back, i’ll do it, but I think it’s better if we do it the python way.

I am quite very well aware of that, but I am strongly against it, at least in my own projects. If you could use tabs, that'd be appreciated, thanks!

**Comment by protodeniz** [comment]
Brilliant. Many thanks!

**Pull request merged**
